### ISSUE TITLE
[BUG] - Custom roster report query returning duplicate entries

### ISSUE THREAD

**Issue by tkhu1** [THE-BWC/OpServ-Issues#32]
### Description

When running the following report, the DB query is returning duplicate table rows. Maybe needs a SELECT Distinct or equivalent clause by default?

![image](https://github.com/THE-BWC/OpServ-Issues/assets/46427408/3e6aecf8-110f-4bbb-af16-2507f3e34e81)

![image](https://github.com/THE-BWC/OpServ-Issues/assets/46427408/0a58f79c-3717-451b-b355-0cf7c6fa50a1)

### Browsers

Chrome

### OS

Windows

**Comment by PatrickPedersen** [comment]
That would be because of the taskforces.
Since certain members are part of multiple taskforces, you end up with what seems like duplicate lines. But if you select Battlegroup, the taskforces they are a part of show up.

An example would be Aniron:
![image](https://github.com/THE-BWC/OpServ-Issues/assets/44923215/3fd61c87-c0ee-466d-a18a-04f869ed653f)
With Battlegroup on, it shows all three taskforces he is a part of.

The only real solution I could provide would be yet another checkbox for "Unique Selection" only. You just need to remember to turn it off, if you want to see all taskforces a member is part of.

**Comment by tkhu1** [comment]
Ok so the workaround is to turn off battlegroup. Could we have battlegroup default to false when loading the report, perhaps?

**Comment by PatrickPedersen** [comment]
Sorry for the long delay. I guess we could default it to false, since battlegroups aren't setup like in the old days anymore.

**Comment by PatrickPedersen** [comment]
@tkhu1 This should work correctly now, with the battlegroups/taskforces turned off by default.

**Comment by tkhu1** [comment]
Thanks, is this deployed now? Or upcoming release?

**Comment by PatrickPedersen** [comment]
Already deployed
